CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    apellido VARCHAR(80) NOT NULL,
    email VARCHAR(160) NOT NULL,
    password VARCHAR(255) NOT NULL,
    telefono VARCHAR(30),
    foto_perfil VARCHAR(500),
    role VARCHAR(30) NOT NULL DEFAULT 'ROLE_USER',
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ROLE_ADMIN', 'ROLE_USER'))
);

CREATE TABLE IF NOT EXISTS refugios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    direccion VARCHAR(180) NOT NULL,
    telefono VARCHAR(30),
    descripcion TEXT,
    latitud NUMERIC(10,7) NOT NULL,
    longitud NUMERIC(10,7) NOT NULL,
    ciudad VARCHAR(80) NOT NULL,
    CONSTRAINT uk_refugios_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    edad INTEGER NOT NULL,
    tipo_edad VARCHAR(12) NOT NULL DEFAULT 'ANIOS',
    raza VARCHAR(80) NOT NULL,
    tamano VARCHAR(20) NOT NULL,
    genero VARCHAR(20) NOT NULL,
    descripcion TEXT,
    estado_salud VARCHAR(120) NOT NULL,
    vacunado BOOLEAN NOT NULL DEFAULT FALSE,
    esterilizado BOOLEAN NOT NULL DEFAULT FALSE,
    imagen_url VARCHAR(500),
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_rescate DATE,
    refugio_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mascotas_refugios FOREIGN KEY (refugio_id) REFERENCES refugios(id),
    CONSTRAINT ck_mascotas_edad CHECK (edad >= 0),
    CONSTRAINT ck_mascotas_tipo_edad CHECK (tipo_edad IN ('MESES', 'ANIOS')),
    CONSTRAINT ck_mascotas_tamano CHECK (tamano IN ('PEQUENO', 'MEDIANO', 'GRANDE')),
    CONSTRAINT ck_mascotas_genero CHECK (genero IN ('MACHO', 'HEMBRA'))
);

CREATE TABLE IF NOT EXISTS solicitudes_adopcion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    mascota_id BIGINT NOT NULL,
    mensaje TEXT NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_solicitudes_adopcion_users FOREIGN KEY (usuario_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_solicitudes_adopcion_mascotas FOREIGN KEY (mascota_id) REFERENCES mascotas(id) ON DELETE CASCADE,
    CONSTRAINT ck_solicitudes_adopcion_estado CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA'))
);

CREATE TABLE IF NOT EXISTS solicitudes_ingreso_mascota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    refugio_id BIGINT NOT NULL,
    nombre_mascota VARCHAR(100) NOT NULL,
    edad INTEGER NOT NULL,
    tipo_edad VARCHAR(12) NOT NULL DEFAULT 'ANIOS',
    raza VARCHAR(80) NOT NULL,
    tamano VARCHAR(20) NOT NULL,
    genero VARCHAR(20) NOT NULL,
    descripcion TEXT NOT NULL,
    estado_salud VARCHAR(120) NOT NULL,
    vacunado BOOLEAN NOT NULL DEFAULT FALSE,
    esterilizado BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_entrega TEXT NOT NULL,
    telefono_contacto VARCHAR(30) NOT NULL,
    direccion VARCHAR(180) NOT NULL,
    imagen_url VARCHAR(500) NOT NULL,
    estado_solicitud VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_solicitudes_ingreso_users FOREIGN KEY (usuario_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_solicitudes_ingreso_refugios FOREIGN KEY (refugio_id) REFERENCES refugios(id),
    CONSTRAINT ck_solicitudes_ingreso_edad CHECK (edad >= 0),
    CONSTRAINT ck_solicitudes_ingreso_tipo_edad CHECK (tipo_edad IN ('MESES', 'ANIOS')),
    CONSTRAINT ck_solicitudes_ingreso_tamano CHECK (tamano IN ('PEQUENO', 'MEDIANO', 'GRANDE')),
    CONSTRAINT ck_solicitudes_ingreso_genero CHECK (genero IN ('MACHO', 'HEMBRA')),
    CONSTRAINT ck_solicitudes_ingreso_estado CHECK (estado_solicitud IN ('PENDIENTE', 'APROBADA', 'RECHAZADA'))
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_refugios_ciudad ON refugios(ciudad);
CREATE INDEX IF NOT EXISTS idx_mascotas_refugio ON mascotas(refugio_id);
CREATE INDEX IF NOT EXISTS idx_mascotas_disponible ON mascotas(disponible);
CREATE INDEX IF NOT EXISTS idx_mascotas_tamano ON mascotas(tamano);
CREATE INDEX IF NOT EXISTS idx_mascotas_genero ON mascotas(genero);
CREATE INDEX IF NOT EXISTS idx_solicitudes_adopcion_usuario ON solicitudes_adopcion(usuario_id);
CREATE INDEX IF NOT EXISTS idx_solicitudes_adopcion_mascota ON solicitudes_adopcion(mascota_id);
CREATE INDEX IF NOT EXISTS idx_solicitudes_adopcion_estado ON solicitudes_adopcion(estado);
CREATE INDEX IF NOT EXISTS idx_solicitudes_ingreso_usuario ON solicitudes_ingreso_mascota(usuario_id);
CREATE INDEX IF NOT EXISTS idx_solicitudes_ingreso_refugio ON solicitudes_ingreso_mascota(refugio_id);
CREATE INDEX IF NOT EXISTS idx_solicitudes_ingreso_estado ON solicitudes_ingreso_mascota(estado_solicitud);
