CREATE SCHEMA IF NOT EXISTS public;

DO $$
BEGIN
    IF to_regclass('public.mascotas') IS NULL AND to_regclass('public.mascota') IS NOT NULL THEN
        ALTER TABLE public.mascota RENAME TO mascotas;
    ELSIF to_regclass('public.mascotas') IS NULL AND to_regclass('public.tbl_mascotas') IS NOT NULL THEN
        ALTER TABLE public.tbl_mascotas RENAME TO mascotas;
    ELSIF to_regclass('public.mascotas') IS NULL AND to_regclass('public."Mascota"') IS NOT NULL THEN
        ALTER TABLE public."Mascota" RENAME TO mascotas;
    END IF;

    IF to_regclass('public.refugios') IS NULL AND to_regclass('public.refugio') IS NOT NULL THEN
        ALTER TABLE public.refugio RENAME TO refugios;
    ELSIF to_regclass('public.refugios') IS NULL AND to_regclass('public.tbl_refugios') IS NOT NULL THEN
        ALTER TABLE public.tbl_refugios RENAME TO refugios;
    ELSIF to_regclass('public.refugios') IS NULL AND to_regclass('public."Refugio"') IS NOT NULL THEN
        ALTER TABLE public."Refugio" RENAME TO refugios;
    END IF;

    IF to_regclass('public.users') IS NULL AND to_regclass('public."user"') IS NOT NULL THEN
        ALTER TABLE public."user" RENAME TO users;
    ELSIF to_regclass('public.users') IS NULL AND to_regclass('public.usuario') IS NOT NULL THEN
        ALTER TABLE public.usuario RENAME TO users;
    ELSIF to_regclass('public.users') IS NULL AND to_regclass('public.usuarios') IS NOT NULL THEN
        ALTER TABLE public.usuarios RENAME TO users;
    END IF;

    IF to_regclass('public.solicitudes_adopcion') IS NULL AND to_regclass('public.solicitud_adopcion') IS NOT NULL THEN
        ALTER TABLE public.solicitud_adopcion RENAME TO solicitudes_adopcion;
    END IF;

    IF to_regclass('public.solicitudes_ingreso_mascota') IS NULL AND to_regclass('public.solicitud_ingreso_mascota') IS NOT NULL THEN
        ALTER TABLE public.solicitud_ingreso_mascota RENAME TO solicitudes_ingreso_mascota;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    apellido VARCHAR(80) NOT NULL,
    email VARCHAR(160) NOT NULL,
    password VARCHAR(255) NOT NULL,
    telefono VARCHAR(30),
    foto_perfil VARCHAR(500),
    role VARCHAR(30) NOT NULL DEFAULT 'ROLE_USER',
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.refugios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    direccion VARCHAR(180) NOT NULL,
    telefono VARCHAR(30),
    descripcion TEXT,
    latitud NUMERIC(10,7) NOT NULL,
    longitud NUMERIC(10,7) NOT NULL,
    ciudad VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    edad INTEGER NOT NULL,
    tipo_edad VARCHAR(12) NOT NULL DEFAULT 'ANIOS',
    raza VARCHAR(80) NOT NULL,
    tamano VARCHAR(20) NOT NULL,
    genero VARCHAR(20) NOT NULL,
    descripcion TEXT,
    estado_salud VARCHAR(120) NOT NULL,
    vacunado BOOLEAN NOT NULL DEFAULT FALSE,
    esterilizado BOOLEAN NOT NULL DEFAULT FALSE,
    imagen_url VARCHAR(500),
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_rescate DATE,
    refugio_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.solicitudes_adopcion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    mascota_id BIGINT NOT NULL,
    mensaje TEXT NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.solicitudes_ingreso_mascota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    refugio_id BIGINT NOT NULL,
    nombre_mascota VARCHAR(100) NOT NULL,
    edad INTEGER NOT NULL,
    tipo_edad VARCHAR(12) NOT NULL DEFAULT 'ANIOS',
    raza VARCHAR(80) NOT NULL,
    tamano VARCHAR(20) NOT NULL,
    genero VARCHAR(20) NOT NULL,
    descripcion TEXT NOT NULL,
    estado_salud VARCHAR(120) NOT NULL,
    vacunado BOOLEAN NOT NULL DEFAULT FALSE,
    esterilizado BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_entrega TEXT NOT NULL,
    telefono_contacto VARCHAR(30) NOT NULL,
    direccion VARCHAR(180) NOT NULL,
    imagen_url VARCHAR(500) NOT NULL,
    estado_solicitud VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS nombre VARCHAR(80),
    ADD COLUMN IF NOT EXISTS apellido VARCHAR(80),
    ADD COLUMN IF NOT EXISTS email VARCHAR(160),
    ADD COLUMN IF NOT EXISTS password VARCHAR(255),
    ADD COLUMN IF NOT EXISTS telefono VARCHAR(30),
    ADD COLUMN IF NOT EXISTS foto_perfil VARCHAR(500),
    ADD COLUMN IF NOT EXISTS role VARCHAR(30) DEFAULT 'ROLE_USER',
    ADD COLUMN IF NOT EXISTS fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.refugios
    ADD COLUMN IF NOT EXISTS nombre VARCHAR(120),
    ADD COLUMN IF NOT EXISTS direccion VARCHAR(180),
    ADD COLUMN IF NOT EXISTS telefono VARCHAR(30),
    ADD COLUMN IF NOT EXISTS descripcion TEXT,
    ADD COLUMN IF NOT EXISTS latitud NUMERIC(10,7),
    ADD COLUMN IF NOT EXISTS longitud NUMERIC(10,7),
    ADD COLUMN IF NOT EXISTS ciudad VARCHAR(80);

ALTER TABLE public.mascotas
    ADD COLUMN IF NOT EXISTS nombre VARCHAR(100),
    ADD COLUMN IF NOT EXISTS edad INTEGER,
    ADD COLUMN IF NOT EXISTS tipo_edad VARCHAR(12) DEFAULT 'ANIOS',
    ADD COLUMN IF NOT EXISTS raza VARCHAR(80),
    ADD COLUMN IF NOT EXISTS tamano VARCHAR(20),
    ADD COLUMN IF NOT EXISTS genero VARCHAR(20),
    ADD COLUMN IF NOT EXISTS descripcion TEXT,
    ADD COLUMN IF NOT EXISTS estado_salud VARCHAR(120),
    ADD COLUMN IF NOT EXISTS vacunado BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS esterilizado BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS imagen_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS disponible BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS fecha_rescate DATE,
    ADD COLUMN IF NOT EXISTS refugio_id BIGINT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.solicitudes_adopcion
    ADD COLUMN IF NOT EXISTS usuario_id BIGINT,
    ADD COLUMN IF NOT EXISTS mascota_id BIGINT,
    ADD COLUMN IF NOT EXISTS mensaje TEXT,
    ADD COLUMN IF NOT EXISTS estado VARCHAR(30) DEFAULT 'PENDIENTE',
    ADD COLUMN IF NOT EXISTS fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.solicitudes_ingreso_mascota
    ADD COLUMN IF NOT EXISTS usuario_id BIGINT,
    ADD COLUMN IF NOT EXISTS refugio_id BIGINT,
    ADD COLUMN IF NOT EXISTS nombre_mascota VARCHAR(100),
    ADD COLUMN IF NOT EXISTS edad INTEGER,
    ADD COLUMN IF NOT EXISTS tipo_edad VARCHAR(12) DEFAULT 'ANIOS',
    ADD COLUMN IF NOT EXISTS raza VARCHAR(80),
    ADD COLUMN IF NOT EXISTS tamano VARCHAR(20),
    ADD COLUMN IF NOT EXISTS genero VARCHAR(20),
    ADD COLUMN IF NOT EXISTS descripcion TEXT,
    ADD COLUMN IF NOT EXISTS estado_salud VARCHAR(120),
    ADD COLUMN IF NOT EXISTS vacunado BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS esterilizado BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS motivo_entrega TEXT,
    ADD COLUMN IF NOT EXISTS telefono_contacto VARCHAR(30),
    ADD COLUMN IF NOT EXISTS direccion VARCHAR(180),
    ADD COLUMN IF NOT EXISTS imagen_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS estado_solicitud VARCHAR(30) DEFAULT 'PENDIENTE',
    ADD COLUMN IF NOT EXISTS fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE public.users SET role = 'ROLE_USER' WHERE role IS NULL OR role = '';
UPDATE public.mascotas SET tipo_edad = 'ANIOS' WHERE tipo_edad IS NULL OR tipo_edad = '';
UPDATE public.mascotas SET vacunado = FALSE WHERE vacunado IS NULL;
UPDATE public.mascotas SET esterilizado = FALSE WHERE esterilizado IS NULL;
UPDATE public.mascotas SET disponible = TRUE WHERE disponible IS NULL;
UPDATE public.mascotas SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE public.solicitudes_adopcion SET estado = 'PENDIENTE' WHERE estado IS NULL OR estado = '';
UPDATE public.solicitudes_adopcion SET fecha_solicitud = CURRENT_TIMESTAMP WHERE fecha_solicitud IS NULL;
UPDATE public.solicitudes_ingreso_mascota SET tipo_edad = 'ANIOS' WHERE tipo_edad IS NULL OR tipo_edad = '';
UPDATE public.solicitudes_ingreso_mascota SET vacunado = FALSE WHERE vacunado IS NULL;
UPDATE public.solicitudes_ingreso_mascota SET esterilizado = FALSE WHERE esterilizado IS NULL;
UPDATE public.solicitudes_ingreso_mascota SET estado_solicitud = 'PENDIENTE' WHERE estado_solicitud IS NULL OR estado_solicitud = '';
UPDATE public.solicitudes_ingreso_mascota SET fecha_solicitud = CURRENT_TIMESTAMP WHERE fecha_solicitud IS NULL;

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_refugios_ciudad ON public.refugios(ciudad);
CREATE INDEX IF NOT EXISTS idx_mascotas_refugio ON public.mascotas(refugio_id);
CREATE INDEX IF NOT EXISTS idx_mascotas_disponible ON public.mascotas(disponible);
CREATE INDEX IF NOT EXISTS idx_mascotas_tamano ON public.mascotas(tamano);
CREATE INDEX IF NOT EXISTS idx_mascotas_genero ON public.mascotas(genero);
CREATE INDEX IF NOT EXISTS idx_solicitudes_adopcion_usuario ON public.solicitudes_adopcion(usuario_id);
CREATE INDEX IF NOT EXISTS idx_solicitudes_adopcion_mascota ON public.solicitudes_adopcion(mascota_id);
CREATE INDEX IF NOT EXISTS idx_solicitudes_adopcion_estado ON public.solicitudes_adopcion(estado);
CREATE INDEX IF NOT EXISTS idx_solicitudes_ingreso_usuario ON public.solicitudes_ingreso_mascota(usuario_id);
CREATE INDEX IF NOT EXISTS idx_solicitudes_ingreso_refugio ON public.solicitudes_ingreso_mascota(refugio_id);
CREATE INDEX IF NOT EXISTS idx_solicitudes_ingreso_estado ON public.solicitudes_ingreso_mascota(estado_solicitud);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM public.users
        WHERE email IS NOT NULL
        GROUP BY email
        HAVING COUNT(*) > 1
    ) THEN
        CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON public.users(email);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.refugios
        WHERE nombre IS NOT NULL
        GROUP BY nombre
        HAVING COUNT(*) > 1
    ) THEN
        CREATE UNIQUE INDEX IF NOT EXISTS uk_refugios_nombre ON public.refugios(nombre);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mascotas_refugios') THEN
        ALTER TABLE public.mascotas
            ADD CONSTRAINT fk_mascotas_refugios FOREIGN KEY (refugio_id) REFERENCES public.refugios(id) NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_solicitudes_adopcion_users') THEN
        ALTER TABLE public.solicitudes_adopcion
            ADD CONSTRAINT fk_solicitudes_adopcion_users FOREIGN KEY (usuario_id) REFERENCES public.users(id) ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_solicitudes_adopcion_mascotas') THEN
        ALTER TABLE public.solicitudes_adopcion
            ADD CONSTRAINT fk_solicitudes_adopcion_mascotas FOREIGN KEY (mascota_id) REFERENCES public.mascotas(id) ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_solicitudes_ingreso_users') THEN
        ALTER TABLE public.solicitudes_ingreso_mascota
            ADD CONSTRAINT fk_solicitudes_ingreso_users FOREIGN KEY (usuario_id) REFERENCES public.users(id) ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_solicitudes_ingreso_refugios') THEN
        ALTER TABLE public.solicitudes_ingreso_mascota
            ADD CONSTRAINT fk_solicitudes_ingreso_refugios FOREIGN KEY (refugio_id) REFERENCES public.refugios(id) NOT VALID;
    END IF;
END $$;
